os:
  - linux
  - windows

language:
  - python

python:
  - "3.6"

sudo: true
  
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa &&
      sudo apt-get update -qq &&
      sudo apt-get install -qq qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev  &&
      sudo apt-get install qttools5-dev-tools make 
    ;
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      make deps dist
    ;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      deploy\windows-build.bat
    ;
    fi

