os:
  - linux
  - osx

osx_image: xcode9.4

language:
  - python

python:
  - "3.6"

sudo: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa &&
      sudo apt-get update -qq &&
      sudo apt-get install -qq qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev  &&
      sudo apt-get install qttools5-dev-tools make
    ;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export PATH="$HOME/Qt/5.11.1/clang_64/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:$PATH"
    ;
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      make deps dist
    ;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      make deps dmg
    ;
    fi
